# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/MiniMediaPlayer.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1000, 1200)
        Form.setMinimumSize(QtCore.QSize(1000, 1200))
        Form.setMaximumSize(QtCore.QSize(1200, 1200))
        Form.setStyleSheet("background-color: #415466;")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setStyleSheet("QTabWidget::pane { border: 0;\n"
"}\n"
"\n"
"QTabBar::tab  {\n"
"    font-weight: bold;\n"
"    background-color: rgb(189, 189, 189);\n"
"    border: 2px solid rgb(189, 189, 189);\n"
"    border-top-left-radius: 4px;\n"
"    border-top-right-radius: 4px;\n"
"    min-width: 8ex;\n"
"    margin-left: 2px;\n"
"    margin-right: 2px;\n"
"    padding: 6px;\n"
"}\n"
"QTabBar::tab:!selected  {\n"
"    font-weight: bold;\n"
"    background-color: rgb(65, 84, 102);\n"
"    color: white;\n"
"    border: 1px solid rgb(189,189,189);\n"
"    border-top-left-radius: 4px;\n"
"    border-top-right-radius: 4px;\n"
"    min-width: 8ex;\n"
"    margin-left: 2px;\n"
"    margin-right: 2px;\n"
"    padding: 6px;\n"
"}\n"
"\n"
"background-color: rgb(189, 189, 189);")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setStyleSheet("background-color: rgb(189, 189, 189);")
        self.tab.setObjectName("tab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.albumArtLabel = QtWidgets.QLabel(self.tab)
        self.albumArtLabel.setMinimumSize(QtCore.QSize(400, 400))
        self.albumArtLabel.setText("")
        self.albumArtLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.albumArtLabel.setObjectName("albumArtLabel")
        self.verticalLayout.addWidget(self.albumArtLabel)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.titleLabel = QtWidgets.QLabel(self.tab)
        self.titleLabel.setStyleSheet("font:bold")
        self.titleLabel.setText("")
        self.titleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.titleLabel.setWordWrap(True)
        self.titleLabel.setObjectName("titleLabel")
        self.verticalLayout.addWidget(self.titleLabel)
        self.artistLabel = QtWidgets.QLabel(self.tab)
        self.artistLabel.setText("")
        self.artistLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.artistLabel.setWordWrap(True)
        self.artistLabel.setObjectName("artistLabel")
        self.verticalLayout.addWidget(self.artistLabel)
        self.albumLabel = QtWidgets.QLabel(self.tab)
        self.albumLabel.setText("")
        self.albumLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.albumLabel.setWordWrap(True)
        self.albumLabel.setObjectName("albumLabel")
        self.verticalLayout.addWidget(self.albumLabel)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.shuffleButton = QtWidgets.QPushButton(self.tab)
        self.shuffleButton.setStyleSheet("QPushButton {background-color: rgb(156, 175, 169)}\n"
"QPushButton::checked {background-color: }")
        self.shuffleButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/resources/images/shuffle.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.shuffleButton.setIcon(icon)
        self.shuffleButton.setIconSize(QtCore.QSize(60, 60))
        self.shuffleButton.setCheckable(True)
        self.shuffleButton.setFlat(True)
        self.shuffleButton.setObjectName("shuffleButton")
        self.horizontalLayout_7.addWidget(self.shuffleButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem1)
        self.previousButton = QtWidgets.QPushButton(self.tab)
        self.previousButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/resources/images/previous.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.previousButton.setIcon(icon1)
        self.previousButton.setIconSize(QtCore.QSize(60, 80))
        self.previousButton.setFlat(True)
        self.previousButton.setObjectName("previousButton")
        self.horizontalLayout_7.addWidget(self.previousButton)
        self.playButton = QtWidgets.QPushButton(self.tab)
        self.playButton.setMinimumSize(QtCore.QSize(60, 60))
        self.playButton.setMaximumSize(QtCore.QSize(100, 100))
        self.playButton.setStyleSheet("QPushButton {background-color: rgb(156, 175, 169)}\n"
"QPushButton::checked {background-color: }")
        self.playButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/resources/images/play_pause.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.playButton.setIcon(icon2)
        self.playButton.setIconSize(QtCore.QSize(80, 80))
        self.playButton.setCheckable(False)
        self.playButton.setAutoDefault(False)
        self.playButton.setFlat(True)
        self.playButton.setObjectName("playButton")
        self.horizontalLayout_7.addWidget(self.playButton)
        self.nextButton = QtWidgets.QPushButton(self.tab)
        self.nextButton.setStyleSheet("QPushButton {background-color: rgb(156, 175, 169)}\n"
"QPushButton::checked {background-color: }")
        self.nextButton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/images/resources/images/next.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.nextButton.setIcon(icon3)
        self.nextButton.setIconSize(QtCore.QSize(60, 80))
        self.nextButton.setCheckable(False)
        self.nextButton.setFlat(True)
        self.nextButton.setObjectName("nextButton")
        self.horizontalLayout_7.addWidget(self.nextButton)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem2)
        self.loopButton = QtWidgets.QPushButton(self.tab)
        self.loopButton.setStyleSheet("QPushButton {background-color: rgb(156, 175, 169)}\n"
"QPushButton::checked {background-color: }")
        self.loopButton.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/images/resources/images/loop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.loopButton.setIcon(icon4)
        self.loopButton.setIconSize(QtCore.QSize(60, 60))
        self.loopButton.setCheckable(False)
        self.loopButton.setFlat(True)
        self.loopButton.setObjectName("loopButton")
        self.horizontalLayout_7.addWidget(self.loopButton)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.audioScroll = QtWidgets.QScrollBar(self.tab)
        self.audioScroll.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(156, 175, 169)")
        self.audioScroll.setMaximum(100)
        self.audioScroll.setOrientation(QtCore.Qt.Horizontal)
        self.audioScroll.setInvertedAppearance(False)
        self.audioScroll.setObjectName("audioScroll")
        self.verticalLayout.addWidget(self.audioScroll)
        self.audioTimeLayout = QtWidgets.QHBoxLayout()
        self.audioTimeLayout.setObjectName("audioTimeLayout")
        self.timeElapsed = QtWidgets.QLabel(self.tab)
        self.timeElapsed.setStyleSheet("font:bold")
        self.timeElapsed.setObjectName("timeElapsed")
        self.audioTimeLayout.addWidget(self.timeElapsed)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.audioTimeLayout.addItem(spacerItem3)
        self.timeRemaining = QtWidgets.QLabel(self.tab)
        self.timeRemaining.setStyleSheet("font:bold")
        self.timeRemaining.setObjectName("timeRemaining")
        self.audioTimeLayout.addWidget(self.timeRemaining)
        self.verticalLayout.addLayout(self.audioTimeLayout)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setStyleSheet("background-color: rgb(189, 189, 189);")
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.activeQueueLabel = QtWidgets.QLabel(self.tab_2)
        self.activeQueueLabel.setStyleSheet("margin-left: 2px;\n"
"font-weight: bold;")
        self.activeQueueLabel.setObjectName("activeQueueLabel")
        self.verticalLayout_4.addWidget(self.activeQueueLabel)
        self.activeQueue = QtWidgets.QListWidget(self.tab_2)
        self.activeQueue.setStyleSheet("background-color: #415466;\n"
"color: white")
        self.activeQueue.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.activeQueue.setFrameShadow(QtWidgets.QFrame.Plain)
        self.activeQueue.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.activeQueue.setObjectName("activeQueue")
        self.verticalLayout_4.addWidget(self.activeQueue)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout_3.addWidget(self.tabWidget)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Mini Media Player"))
        self.timeElapsed.setText(_translate("Form", "00:00"))
        self.timeRemaining.setText(_translate("Form", "00:00"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "Player"))
        self.activeQueueLabel.setText(_translate("Form", "Queue"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "Queue"))
import resources_rc
