# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/Preferences.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(618, 253)
        Dialog.setStyleSheet("background-color: #415466")
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setMinimumSize(QtCore.QSize(0, 0))
        self.label.setMaximumSize(QtCore.QSize(16777215, 100))
        self.label.setStyleSheet("font: italic;\n"
"color: white")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.addPathButton = QtWidgets.QPushButton(Dialog)
        self.addPathButton.setMaximumSize(QtCore.QSize(200, 16777215))
        self.addPathButton.setStyleSheet("color:white")
        self.addPathButton.setObjectName("addPathButton")
        self.horizontalLayout.addWidget(self.addPathButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.pathListWidget = QtWidgets.QListWidget(Dialog)
        self.pathListWidget.setStyleSheet("color:white")
        self.pathListWidget.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.pathListWidget.setObjectName("pathListWidget")
        self.verticalLayout.addWidget(self.pathListWidget)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setStyleSheet("color:white;\n"
" font:italic")
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.playlistPathLineEdit = QtWidgets.QLineEdit(Dialog)
        self.playlistPathLineEdit.setMinimumSize(QtCore.QSize(800, 0))
        self.playlistPathLineEdit.setStyleSheet("color:white")
        self.playlistPathLineEdit.setObjectName("playlistPathLineEdit")
        self.verticalLayout.addWidget(self.playlistPathLineEdit)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setMinimumSize(QtCore.QSize(600, 0))
        self.buttonBox.setStyleSheet("color:white")
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Preferences"))
        self.label.setText(_translate("Dialog", "Edit Library Path"))
        self.addPathButton.setText(_translate("Dialog", "Add Path"))
        self.label_2.setText(_translate("Dialog", "Edit Playlist Directory"))
